### ISSUE TITLE
How to use other api features like getting playlist etc?

### ISSUE THREAD

**Issue by ayyazzafar** [pmwisdom/cordova-spotify-plugin#2]
I liked simplicity of this plugin. But I am curious to know that after login If I use other features of spotify api then how can I do that?

I your descriptions I don't see option to use other options like getting play list etc.

**Comment by pmwisdom** [comment]
Hi @ayyazzafar I specifically left them out, because you can very easily get all that information from the web API! The one thing you cannot do with the web api is play full songs, which this handles.

I was developing a very small personal app so I didn't want to overlap features when they're already currently accessible through the web api.

**Comment by pmwisdom** [comment]
https://developer.spotify.com/web-api/

**Comment by ayyazzafar** [comment]
Thanks for quick response and for great plugin. I really appreciate.

**Comment by ayyazzafar** [comment]
btw will Spotify.login(); return any token which I could use in web api? or will I have to prompt for login again for using web-api?

**Comment by pmwisdom** [comment]
An authentication token will get passed back through the login callback, I just editted the docs to reflect that.

**Comment by ayyazzafar** [comment]
Awesome! I saw updated docs. It really helped me a lot. Thanks again for your efforts and time.
